name: First Workflow

on:
  - push

jobs: 
  name: RAff-Jomacs
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: First Message
              run: echo "Welcome to the World of CICD through Github Actions"

            - name: List All Files including Hidden 
              run: ls -1a

            - name: Show Present Working Directory
              run: pwd